name: Release and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  release-and-deploy:
    uses: nizarcan/reusable-actions/.github/workflows/release-deploy.yml@main
    with:
        runner: 'ubuntu-latest'
        image_description: 'NGINX static site container'
        platforms: 'linux/amd64,linux/arm64'